#!/usr/bin/with-contenv bash

if [ ! -d "/config/.sopel" ]; then
    mkdir -p /config/.sopel/log
    cp /defaults/default.cfg /config/.sopel/
fi
if [ ! -d "/config/.sopel/logs" ]; then
    mkdir -p /config/.sopel/logs
fi